language: node_js
node_js:
  - "8" # use older version to try to avoid weird version conflict
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_PRODUCTION_TOKEN