language: node_js
node_js:
  - "node" # latest version
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@5.6.0
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_PRODUCTION_TOKEN